### ISSUE TITLE
TDMS_export tool only creates headers

### ISSUE THREAD

**Issue by kferrari** [Neurotar/locomotion-tracking-software#33]
Hi Dmytro

I tried the TDMS export tool from [v0.9.1.1](https://github.com/Neurotar/locomotion-tracking-software/tree/v0.9.1.1) and it unfortunately only saves the header in the output CSV, but not the values. There's an error in the errors array. Please see attached picture. Do you have any idea what's going wrong? I'm using Windows 7.

![image](https://user-images.githubusercontent.com/6538147/72332823-02ae8f00-36bb-11ea-8deb-c2c893eab19b.png)

**Comment by dmitriy-t** [comment]
Hi Kim,

As of today, TDMS export tool is compatible only with the software versions
up to 2.1.10.3.
We think that direct import should be generally easier for users, because
you do not need an extra step. That is why:

With the newer versions of the software there is an automatically installed
plugin, which allows open TDMS just in Excel (usually Excel can digest up
to ~15-20 min tracks).
There a very nice Python package for interacting with TDMS:
https://pypi.org/project/npTDMS/ (you should use "Raw_sensor_data", "Data"
or "Pp_Data" as a group name). For channel names, you can use the column
names from Excel (or I will send you a reference later this week (new
version is about to release)).
In case if you are Matlab user, you can try
https://se.mathworks.com/matlabcentral/fileexchange/30023-tdms-reader
There is also a package for R (not tested, but this is basically a port of
npTDMS): https://github.com/msuefishlab/tdmsreader

If you think that we are not right about this / this is not handy /
something else, don't hesitate to share your thoughts.

Kind regards,
Dmytro

**Comment by kferrari** [comment]
Hi Dmytro

Thank you very much for the fast response. I wasn't aware that the export tool isn't compatible with more recent versions, thanks for pointing that out.

I tried three of the tools you suggested and just for completeness briefly wanted to report here:

- [R package](https://github.com/msuefishlab/tdmsreader) errors when loading a track file with error

```
Error in if (self$data_type$name == "tdsTypeString") { : 
  argument is of length zero
```

- [MATLAB TDMS reader](https://se.mathworks.com/matlabcentral/fileexchange/30023-tdms-reader) loads file fine, but the resulting struct is a bit complex.

- [npTDMS](https://pypi.org/project/npTDMS/) package for Python works very well!


As I still want to work in R, I use the following snippet, modified from [here](https://github.com/CommerceDataService/netZero/blob/master/convert_tdms_to_csv.py)

```
#!/usr/bin/env python

from nptdms import TdmsFile
import glob
import re
from tkinter import filedialog
from tkinter import *

root = Tk()

# Ask for input directory
input_dir = filedialog.askdirectory()

# Crawl recursively to find all *.tdms files (max. 4 layers deep)
for filename in glob.iglob(input_dir+'/**/**/**/*.tdms', recursive=True): 
    tdms_file = TdmsFile(filename)
    temp = tdms_file.as_dataframe(time_index=False, absolute_time=False)
    temp.to_csv(path_or_buf=(filename.replace(".tdms", ".csv")), encoding='utf-8')
    
# Close orphaned tkinter window
root.destroy()
```


In my opinion, a text-based format such as CSV (or probably even better JSON) would make the data even more accessible, as it can be more easily loaded in other applications. But I see that, as the Tracker works in LabView, it is a lot handier to export it as TDMS.

Thanks again, I think the issue can be closed.

Best,
Kim

**Comment by dmitriy-t** [comment]
Hi Kim,

Thanks a lot for testing R solution! And yes, npTDMS works like a charm :)

Concerning confusion with TDMS export tool: we will add a note to the
release page.

Concerning export in different formats: we will add an instructions into
the latest version of the manual (most likely will be released this week).
In general, I've just added CSV and JSON export (with columns and/or range
selection) to our development pipeline, but at the moment there is no
specific release date for this.

Meanwhile, version 2.2.0.9 is released:
https://github.com/Neurotar/locomotion-tracking-software/releases/tag/2.2.0.9

All the best,
Dmytro

**Comment by dmitriy-t** [comment]
Feature request added to pipeline (see above).

**Comment by kferrari** [comment]
Thanks a lot, Dmytro!

**Comment by dmitriy-t** [comment]
Made a really quick test with CSV/JSON/XML export. Looks like this is
possible. Interesting, that TDMS is the most compact format.
If we assume that TMDS is 100% in size, then:

   - CSV/text: 145%
   - JSON: 273%
   - XML: 755%

Generally, should not be a problem for modern computers, of course.

**Comment by kferrari** [comment]
Great to hear it's possible! 
Yes, I also noticed that the CSV is quite a bit larger than TDMS. When I converted to a data frame with npTDMS and then saved, the CSVs were roughly 200% the size of TDMS.
