### ISSUE TITLE
X1_raw and Y1_raw vs. X and Y

### ISSUE THREAD

**Issue by IljaPilja** [Neurotar/locomotion-tracking-software#39]
Hi,
I've been using the HomeCage for a while now but recently I've noticed that even though the mouse is all the way near the edge of the tray, the Canvas window shows that it is still a ways from the edge. What I did is that I recorded some tracking data without a mouse in the device by moving the tray (diameter 325 mm) along the edge for 360 degrees. It seems I must somehow have not set something right because the canvas window indicated that I was going beyond the size of the tray. I did have the bridge moved away from the zero position at 25, which I did set in the appropriate GUI. I thought all I had to set was the correct size of the tray that I was using and the offset of the bridge if any. I guess I was wrong. By re-examining my locomotion data it seems that the X and Y coordinates did clip those values that went beyond the tray.  I need all the data though and I need to be able to reconstruct the data even though my settings had been wrong. This I thought could be done by using the X1_raw and Y1_raw data within the track.tdms file. Using the test data (where I moved the tray manually around), I was able to retrieve the clipped data points, see below:

![Locomotion_test_BridgeOffset_25_Tray325mm](https://user-images.githubusercontent.com/35040409/84582031-f9c60480-ada3-11ea-9294-7fdedaf8b268.png)

However, re-examining my actual data (here the bridge was set to 0, thus no offset was used)
, I noticed that the raw (right plot) versus the filtered coordinates (left plot) are very different, see below (could not save as png because file seems to be extremely large, that is the reason for the foto):

![IMG_20200613_183839294](https://user-images.githubusercontent.com/35040409/84582155-a9e83d00-ada5-11ea-8164-7d4b108277ab.jpg)

I need desperately to retrieve the entire x,y coordinates that are recorded prior to any filtering so that I can reconstruct the zones and determine which coordinates are in each. Please tell me that that is possible.

Thank you very much, 
Ilja

**Comment by dmitriy-t** [comment]
Hi Ilja, 

Reconstruction of X and Y from the raw data is possible, no worries. I will write you back with instructions a bit later.

Kind regards,
Dmytro

**Comment by dmitriy-t** [comment]
Hello Ilja,

You can find some additional information about the meaning of the specific
variables in the saved data on the pages 17 and 18 of the manual (Help ->
Open Manual in the software).
But in a short:

   - X1 raw, Y1 raw, X2 raw, Y2 raw - this is not the coordinates of the
   mouse. This is the coordinates of the magnets, in-built into the flying
   cage. They still need to be processed in order to get the mouse's
   coordinates (that is why you have very different results between X1... etc
   and filtered data).
   - Trajectory, that you see on the canvas represents the position of the
   mouse's craniotomy, i.e. the place where the microscope is looking at. So,
   even with all settings set absolutely correct, track may not touch the edge
   of the canvas. If some of the settings are incorrect (especially bridge
   offsets), trajectory may change its scale and/or being offset from the
   normal location.

Fortunately, almost in every case it is possible to re-calculate
coordinates from the raw data. For this you need to know real hardware
bridge offset (if any). If this offset is not known, in most cases it can
be guessed from the long enough track. The bad side is that we do not have
a standard tool for such re-calculation, i.e. such conversion should be
implemented elsewhere manually (i.e. in Python or R, etc.). Please let me
know if you need help with that.

Kind regards,
Dmytro

**Comment by IljaPilja** [comment]
Hi,
I'm not so sure if I need to re-calculate the X and Y-coordinates. The only parameters that I set upon starting the recordings were the Bridge offset, set to +25 because I moved it towards me to get the mouse in the device more easily and I set the diameter of the tray to 325 mm. I did not change any of the horizontal settings. Using these settings and moving the tray manually I clearly see that the trajectory of the movements goes outside of the canvas window illustration, see density map (time) below:

![density_map_(time)](https://user-images.githubusercontent.com/35040409/84674122-cd1b0580-aee7-11ea-85d6-a43fc42ea2c0.png)

I assume I need to adjust the coordinates and thus I do need help in this conversion. I use Python and it would be really great if you could help me out in this.

Thanks,
Ilja

**Comment by dmitriy-t** [comment]
Aha, now I understand. Sure, I'll help. Python is fine, a good opportunity to write a conversion function/class or something like that. Could you please share some track (all folder), so we would be working on the same data?

Kind regards,
Dmytro
________________________________
